name: photo_manager
description: You can scan photos and albums. Only api, not have ui. you can use the api to create your image picker. or use photo
version: 1.2.7
homepage: https://github.com/CaiJingLong/flutter_photo_manager
# author: caijinglong<cjl_spy@163.com>

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: top.kikt.imagescanner
        pluginClass: ImageScannerPlugin
      ios:
        pluginClass: ImageScannerPlugin
      macos:
        pluginClass: ImageScannerPlugin
